version: '3.8'
services:

  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nestjs:
    image: dakeinu/backskinsight:latest
    build: .
    container_name: backskinsight
    restart: always
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/median-db
    ports:
      - '3002:3002'
    depends_on:
      - postgres

volumes:
  postgres:
