version: '3.8'
services:

  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  
  nestjs:
    image: dakeinu/backskinsight:latest
    container_name: backskinsight
    build: .
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '3000:3000'
    depends_on:
      - postgres

volumes:
  postgres:
