name: Snyk Security Check

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
  
      - name: "Install"
        run: "npm install"
      
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --fail-on=all
  
      - name: Run Snyk Code Analytics
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # Assurez-vous de configurer cela dans les secrets de votre dépôt
        with:
          command: code test
